services:
  db_test:
    image: postgres:16
    container_name: ecommerce_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: ecommerce_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_test"]
      interval: 2s
      timeout: 2s
      retries: 20
